### ISSUE TITLE
Causes NodeBB to Crash on 0.9.0

### ISSUE THREAD

**Issue by scottalanmiller** [Schamper/nodebb-plugin-poll#35]
Plugin seems to work until we try to make a poll them the post is unable to save.  Instead NodeBB crashes out and restarts.  First we get a 502, then a 503, then the site returns but the poll never posts.

**Comment by manV** [comment]
Here is detailed error

18/11 07:02 [24655] - error: TypeError: Cannot read property 'end' of undefined
    at /home/ubuntu/latest-nodebb/node_modules/nodebb-plugin-poll/lib/backend.js:47:29
    at /home/ubuntu/latest-nodebb/src/database/mongo/hash.js:245:4
    at handleCallback (/home/ubuntu/latest-nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/ubuntu/latest-nodebb/node_modules/mongodb/lib/collection.js:2330:14
    at handleCallback (/home/ubuntu/latest-nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/ubuntu/latest-nodebb/node_modules/mongodb/lib/db.js:283:5
    at /home/ubuntu/latest-nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:765:13
    at Callbacks.emit (/home/ubuntu/latest-nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/
server.js:95:3)
    at null.messageHandler (/home/ubuntu/latest-nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topolo
gies/server.js:243:23)
    at Socket.<anonymous> (/home/ubuntu/latest-nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connect
ion/connection.js:262:22)
TypeError: Cannot read property 'end' of undefined
    at /home/ubuntu/latest-nodebb/node_modules/nodebb-plugin-poll/lib/backend.js:47:29
    at /home/ubuntu/latest-nodebb/src/database/mongo/hash.js:245:4
    at handleCallback (/home/ubuntu/latest-nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/ubuntu/latest-nodebb/node_modules/mongodb/lib/collection.js:2330:14
    at handleCallback (/home/ubuntu/latest-nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/ubuntu/latest-nodebb/node_modules/mongodb/lib/db.js:283:5
    at /home/ubuntu/latest-nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:765:13
    at Callbacks.emit (/home/ubuntu/latest-nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/
server.js:95:3)
    at null.messageHandler (/home/ubuntu/latest-nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/home/ubuntu/latest-nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connect
ion/connection.js:262:22)
18/11 07:02 [24655] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
18/11 07:02 [24655] - error: Error indexing server 127.0.0.1:27017 sockets closed
18/11 07:02 [24655] - info: [app] Database connection closed.
18/11 07:02 [24655] - info: [app] Web server closed to connections.
18/11 07:02 [24655] - info: [app] Shutdown complete.

**Comment by Schamper** [comment]
This is fixed in the version over at the development branch. When it's published and you still encounter this issue you can reopen it.
