### ISSUE TITLE
Dev Branch Error

### ISSUE THREAD

**Issue by whittssg** [Schamper/nodebb-plugin-poll#45]
When hitting submit after saving the poll my nodebb app crashes.. This is the output that i get:

8/1 12:53 [12100] - error: TypeError: Cannot set property 'title' of undefined
    at C:\Apps\nodebb\node_modules\nodebb-plugin-poll\public\js\poll\serializer.js:119:16
    at Function.self.forEach (C:\Apps\nodebb\node_modules\xregexp\xregexp-all.js:907:13)
    at serializeSettings (C:\Apps\nodebb\node_modules\nodebb-plugin-poll\public\js\poll\serializer.js:113:18)
    at Object.Serializer.serialize (C:\Apps\nodebb\node_modules\nodebb-plugin-poll\public\js\poll\serializer.js:63:14)
    at C:\Apps\nodebb\node_modules\nodebb-plugin-poll\lib\hooks.js:23:30
    at C:\Apps\nodebb\src\database\mongo\hash.js:71:4
    at handleCallback (C:\Apps\nodebb\node_modules\mongodb\lib\utils.js:96:12)
    at C:\Apps\nodebb\node_modules\mongodb\lib\collection.js:1335:5
    at handleCallback (C:\Apps\nodebb\node_modules\mongodb\lib\utils.js:96:12)
    at C:\Apps\nodebb\node_modules\mongodb\lib\cursor.js:665:5
TypeError: Cannot set property 'title' of undefined
    at C:\Apps\nodebb\node_modules\nodebb-plugin-poll\public\js\poll\serializer.js:119:16
    at Function.self.forEach (C:\Apps\nodebb\node_modules\xregexp\xregexp-all.js:907:13)
    at serializeSettings (C:\Apps\nodebb\node_modules\nodebb-plugin-poll\public\js\poll\serializer.js:113:18)
    at Object.Serializer.serialize (C:\Apps\nodebb\node_modules\nodebb-plugin-poll\public\js\poll\serializer.js:63:14)
    at C:\Apps\nodebb\node_modules\nodebb-plugin-poll\lib\hooks.js:23:30
    at C:\Apps\nodebb\src\database\mongo\hash.js:71:4
    at handleCallback (C:\Apps\nodebb\node_modules\mongodb\lib\utils.js:96:12)
    at C:\Apps\nodebb\node_modules\mongodb\lib\collection.js:1335:5
    at handleCallback (C:\Apps\nodebb\node_modules\mongodb\lib\utils.js:96:12)
    at C:\Apps\nodebb\node_modules\mongodb\lib\cursor.js:665:5
8/1 12:53 [12100] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.

Thanks

**Comment by Schamper** [comment]
What was the markup you used?

**Comment by whittssg** [comment]
I have tried multiple types of Poll and they all do the same thing:

[poll title="Test Poll" maxvotes="1"]
- A
- B
- C
[/poll]

After clicking submit.. the forum crashes - when it comes back up the post is there but appears to be blank until you click edit - once you click edit you see the markup above. 

I installed it by clicking the dev branch, downloading the zip and placing the unzipped folder in the node-modules folder.

**Comment by Schamper** [comment]
I'll test later but in the mean time can you try and go into the config page and change some of the defaults and save it?

**Comment by whittssg** [comment]
I went into the settings and tried saving and then saving with some defaults.. Still the same issue. Thanks

**Comment by whittssg** [comment]
I went ahead and tried it on my live server which is the latest master and its the same issue as my 0.9.1 dev server.. Thanks
