### ISSUE TITLE
Unable to create poll. Call to undefined function

### ISSUE THREAD

**Issue by MrHalfman** [Schamper/nodebb-plugin-poll#90]
Hi, when I try to create a new poll I get this error when I click on the create button : 
```
Uncaught TypeError: n.stripHTMLTags is not a function
    at serializer.js:104
    at Array.map (<anonymous>)
    at c (serializer.js:103)
    at Object.i.deserialize (serializer.js:72)
    at creator.js:92
    at v.fn.init.callback (creator.js:152)
    at s (bootbox.js:101)
    at HTMLButtonElement.<anonymous> (bootbox.js:707)
    at HTMLDivElement.dispatch (jquery.js:5206)
    at HTMLDivElement.g.handle (jquery.js:5014)
```

It seems that the plugin is calling an undefined function (Maybe you should use utils.stripTags ?)

I'm using NodeBB 1.6.1 with nodebb-plugin-polls version 0.2.15

Thanks for your help!

**Comment by ELadner** [comment]
I've seen the same..  here's a slightly more detailed stack trace..

```
20/11 17:35:45 [4350] - error:  TypeError: utils.stripHTMLTags is not a function
    at serializeOptions (/opt/nodebb/node_modules/nodebb-plugin-poll/public/js/poll/serializer.js:80:26)
    at Object.Serializer.serialize (/opt/nodebb/node_modules/nodebb-plugin-poll/public/js/poll/serializer.js:66:13)
    at savePoll (/opt/nodebb/node_modules/nodebb-plugin-poll/lib/hooks.js:106:29)
    at Object.Hooks.filter.postCreate [as method] (/opt/nodebb/node_modules/nodebb-plugin-poll/lib/hooks.js:18:4)
    at /opt/nodebb/src/plugins/hooks.js:122:12
    at /opt/nodebb/node_modules/async/dist/async.js:2489:9
    at replenish (/opt/nodebb/node_modules/async/dist/async.js:946:17)
    at /opt/nodebb/node_modules/async/dist/async.js:950:9
    at eachOfLimit (/opt/nodebb/node_modules/async/dist/async.js:975:24)
    at /opt/nodebb/node_modules/async/dist/async.js:980:16
    at Object.reduce (/opt/nodebb/node_modules/async/dist/async.js:2488:5)
    at fireFilterHook (/opt/nodebb/src/plugins/hooks.js:114:9)
    at Object.Plugins.fireHook (/opt/nodebb/src/plugins/hooks.js:95:4)
    at async.waterfall.postData (/opt/nodebb/src/posts/create.js:63:13)
    at nextTask (/opt/nodebb/node_modules/async/dist/async.js:5297:14)
    at next (/opt/nodebb/node_modules/async/dist/async.js:5304:9)
20/11 17:35:45 [4350] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
20/11 17:35:45 [4350] - info: [app] Database connection closed.
20/11 17:35:45 [4350] - info: [app] Web server closed to connections.
```

**Comment by Schamper** [comment]
@aStonedPenguin I believe this was introduced by you.

**Comment by MrHalfman** [comment]
Upgrading to 1.7.0 fixed the problem for me 😄

**Comment by aStonedPenguin** [comment]
I may have forgot to up the compatibility version oops
